name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Log Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Log installed packages
        run: npm list

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy

      - name: Deployment complete
        run: echo "Deployment to Cloudflare Workers completed successfully."