name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Navigate to backend folder
      - name: Navigate to backend folder
        run: cd backend

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # Step 5: Install Wrangler globally
      - name: Install Wrangler
        run: npm install -g wrangler

      # Step 6: Authenticate Wrangler with Cloudflare API token
      - name: Authenticate Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler login

      # Step 7: Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler publish
        working-directory: backend