name: Cloudflare Worker

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4

    - name: Location
      run: pwd

    - name: Deploy 
      uses: cloudflare/wrangler-action@v3
      with:

        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        workingDirectory: /backend
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
